"""add_tally_fields_and_credit_session_linkage

Revision ID: 1bb8bc050dad
Revises: 72771b38583e
Create Date: 2026-09-01 10:17:12.700887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1bb8bc050dad'
down_revision: Union[str, Sequence[str], None] = '72771b38583e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_bank_dep_date'), table_name='bank_deposits')
    op.drop_column('bank_deposits', 'created_at')
    op.drop_index(op.f('idx_credit_pay_date'), table_name='credit_payments')
    op.add_column('credit_transactions', sa.Column('attribution_id', sa.String(length=20), nullable=True))
    op.add_column('credit_transactions', sa.Column('shift_type', sa.String(length=30), nullable=True))
    op.add_column('credit_transactions', sa.Column('vehicle_number', sa.String(length=50), nullable=True))
    op.alter_column('credit_transactions', 'pump_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_index(op.f('idx_credit_tx_date'), table_name='credit_transactions')
    op.create_foreign_key(None, 'credit_transactions', 'pump_day_attribution', ['attribution_id'], ['id'])
    op.alter_column('daily_cash_reconciliation', 'bunk_expenses',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('daily_cash_reconciliation', 'bata',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('daily_cash_reconciliation', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('daily_cash_reconciliation_recon_date_branch_id_key'), 'daily_cash_reconciliation', type_='unique')
    op.drop_index(op.f('idx_dcr_date'), table_name='daily_cash_reconciliation')
    op.create_index(op.f('ix_daily_cash_reconciliation_branch_id'), 'daily_cash_reconciliation', ['branch_id'], unique=False)
    op.create_unique_constraint('uq_dcr_date_branch', 'daily_cash_reconciliation', ['recon_date', 'branch_id'])
    op.drop_constraint(op.f('daily_cash_reconciliation_branch_id_fkey'), 'daily_cash_reconciliation', type_='foreignkey')
    op.create_foreign_key(None, 'daily_cash_reconciliation', 'branches', ['branch_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('idx_dnm_date'), table_name='daily_nozzle_meters')
    op.drop_index(op.f('idx_dnm_pump'), table_name='daily_nozzle_meters')
    op.drop_constraint(op.f('uq_branch_reading_nozzle'), 'daily_nozzle_meters', type_='unique')
    op.create_unique_constraint('uq_dnm_date_nozzle', 'daily_nozzle_meters', ['reading_date', 'nozzle_id'])
    op.alter_column('expense_types', 'branch_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_index(op.f('ix_expense_types_branch_id'), table_name='expense_types')
    op.drop_index(op.f('idx_expenses_date'), table_name='expenses')
    op.drop_index(op.f('idx_expenses_type'), table_name='expenses')
    op.drop_constraint(op.f('uq_fuel_rate_hist'), 'fuel_rate_history', type_='unique')
    op.create_index(op.f('ix_fuel_rate_history_branch_id'), 'fuel_rate_history', ['branch_id'], unique=False)
    op.create_unique_constraint('uq_rate_hist', 'fuel_rate_history', ['product_id', 'effective_date', 'branch_id'])
    op.create_foreign_key(None, 'fuel_rate_history', 'branches', ['branch_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('uq_branch_pump_nozzle'), 'nozzles', type_='unique')
    op.create_unique_constraint('uq_pump_product_nozzle', 'nozzles', ['pump_id', 'product_id', 'nozzle_no'])
    op.add_column('pump_day_attribution', sa.Column('shift_type', sa.String(length=30), nullable=True))
    op.add_column('pump_day_attribution', sa.Column('advance_amount', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0'))
    op.add_column('pump_day_attribution', sa.Column('actual_cash_handover', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('pump_day_attribution', sa.Column('meter_sales_amount', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('pump_day_attribution', sa.Column('expected_cash_handover', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('pump_day_attribution', sa.Column('cash_variance', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('pump_day_attribution', sa.Column('meter_variance', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('pump_day_attribution', sa.Column('status', sa.String(length=30), nullable=False, server_default='DRAFT'))
    op.add_column('pump_day_attribution', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('pump_day_attribution', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('pump_day_attribution', 'gpay_collected',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('pump_day_attribution', 'phone_pay_collected',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('pump_day_attribution', 'paytm_collected',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('pump_day_attribution', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_pda_date'), table_name='pump_day_attribution')
    op.drop_index(op.f('idx_pda_operator'), table_name='pump_day_attribution')
    op.drop_index(op.f('idx_pda_pump'), table_name='pump_day_attribution')
    op.create_index(op.f('ix_pump_day_attribution_branch_id'), 'pump_day_attribution', ['branch_id'], unique=False)
    op.drop_constraint(op.f('pump_day_attribution_branch_id_fkey'), 'pump_day_attribution', type_='foreignkey')
    op.create_foreign_key(None, 'pump_day_attribution', 'branches', ['branch_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('uq_branch_pump_no', 'pumps', ['pump_no', 'branch_id'])
    op.alter_column('settlements', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_settlements_bank'), table_name='settlements')
    op.drop_index(op.f('idx_settlements_date'), table_name='settlements')
    op.drop_constraint(op.f('settlements_settlement_date_bank_code_channel_code_branch_i_key'), 'settlements', type_='unique')
    op.create_index(op.f('ix_settlements_branch_id'), 'settlements', ['branch_id'], unique=False)
    op.create_unique_constraint('uq_settlement_date_bank_channel', 'settlements', ['settlement_date', 'bank_code', 'channel_code', 'branch_id'])
    op.drop_constraint(op.f('settlements_branch_id_fkey'), 'settlements', type_='foreignkey')
    op.create_foreign_key(None, 'settlements', 'branches', ['branch_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('ck_users_employment_status'), 'users', type_='check')
    op.drop_column('users', 'employment_status')
    op.drop_column('users', 'dob')
    # Remove Bata as an expense head — advance amounts are now tracked on operator sessions
    op.execute("DELETE FROM expense_types WHERE LOWER(name) LIKE '%bata%'")
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dob', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('employment_status', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_check_constraint(op.f('ck_users_employment_status'), 'users', 'employment_status = ANY (ARRAY[0, 1])')
    op.drop_constraint(None, 'settlements', type_='foreignkey')
    op.create_foreign_key(op.f('settlements_branch_id_fkey'), 'settlements', 'branches', ['branch_id'], ['id'])
    op.drop_constraint('uq_settlement_date_bank_channel', 'settlements', type_='unique')
    op.drop_index(op.f('ix_settlements_branch_id'), table_name='settlements')
    op.create_unique_constraint(op.f('settlements_settlement_date_bank_code_channel_code_branch_i_key'), 'settlements', ['settlement_date', 'bank_code', 'channel_code', 'branch_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_settlements_date'), 'settlements', ['settlement_date'], unique=False)
    op.create_index(op.f('idx_settlements_bank'), 'settlements', ['bank_code'], unique=False)
    op.alter_column('settlements', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_branch_pump_no', 'pumps', type_='unique')
    op.drop_constraint(None, 'pump_day_attribution', type_='foreignkey')
    op.create_foreign_key(op.f('pump_day_attribution_branch_id_fkey'), 'pump_day_attribution', 'branches', ['branch_id'], ['id'])
    op.drop_index(op.f('ix_pump_day_attribution_branch_id'), table_name='pump_day_attribution')
    op.create_index(op.f('idx_pda_pump'), 'pump_day_attribution', ['pump_id'], unique=False)
    op.create_index(op.f('idx_pda_operator'), 'pump_day_attribution', ['operator_id'], unique=False)
    op.create_index(op.f('idx_pda_date'), 'pump_day_attribution', ['attribution_date'], unique=False)
    op.alter_column('pump_day_attribution', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('pump_day_attribution', 'paytm_collected',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('pump_day_attribution', 'phone_pay_collected',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('pump_day_attribution', 'gpay_collected',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('pump_day_attribution', 'updated_at')
    op.drop_column('pump_day_attribution', 'notes')
    op.drop_column('pump_day_attribution', 'status')
    op.drop_column('pump_day_attribution', 'meter_variance')
    op.drop_column('pump_day_attribution', 'cash_variance')
    op.drop_column('pump_day_attribution', 'expected_cash_handover')
    op.drop_column('pump_day_attribution', 'meter_sales_amount')
    op.drop_column('pump_day_attribution', 'actual_cash_handover')
    op.drop_column('pump_day_attribution', 'advance_amount')
    op.drop_column('pump_day_attribution', 'shift_type')
    op.drop_constraint('uq_pump_product_nozzle', 'nozzles', type_='unique')
    op.create_unique_constraint(op.f('uq_branch_pump_nozzle'), 'nozzles', ['branch_id', 'pump_id', 'nozzle_no'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'fuel_rate_history', type_='foreignkey')
    op.drop_constraint('uq_rate_hist', 'fuel_rate_history', type_='unique')
    op.drop_index(op.f('ix_fuel_rate_history_branch_id'), table_name='fuel_rate_history')
    op.create_unique_constraint(op.f('uq_fuel_rate_hist'), 'fuel_rate_history', ['product_id', 'effective_date', 'branch_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_expenses_type'), 'expenses', ['expense_type_id'], unique=False)
    op.create_index(op.f('idx_expenses_date'), 'expenses', ['date'], unique=False)
    op.create_index(op.f('ix_expense_types_branch_id'), 'expense_types', ['branch_id'], unique=False)
    op.alter_column('expense_types', 'branch_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_constraint('uq_dnm_date_nozzle', 'daily_nozzle_meters', type_='unique')
    op.create_unique_constraint(op.f('uq_branch_reading_nozzle'), 'daily_nozzle_meters', ['branch_id', 'reading_date', 'nozzle_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_dnm_pump'), 'daily_nozzle_meters', ['pump_id'], unique=False)
    op.create_index(op.f('idx_dnm_date'), 'daily_nozzle_meters', ['reading_date'], unique=False)
    op.drop_constraint(None, 'daily_cash_reconciliation', type_='foreignkey')
    op.create_foreign_key(op.f('daily_cash_reconciliation_branch_id_fkey'), 'daily_cash_reconciliation', 'branches', ['branch_id'], ['id'])
    op.drop_constraint('uq_dcr_date_branch', 'daily_cash_reconciliation', type_='unique')
    op.drop_index(op.f('ix_daily_cash_reconciliation_branch_id'), table_name='daily_cash_reconciliation')
    op.create_index(op.f('idx_dcr_date'), 'daily_cash_reconciliation', ['recon_date'], unique=False)
    op.create_unique_constraint(op.f('daily_cash_reconciliation_recon_date_branch_id_key'), 'daily_cash_reconciliation', ['recon_date', 'branch_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('daily_cash_reconciliation', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('daily_cash_reconciliation', 'bata',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('daily_cash_reconciliation', 'bunk_expenses',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'credit_transactions', type_='foreignkey')
    op.create_index(op.f('idx_credit_tx_date'), 'credit_transactions', ['date'], unique=False)
    op.alter_column('credit_transactions', 'pump_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('credit_transactions', 'vehicle_number')
    op.drop_column('credit_transactions', 'shift_type')
    op.drop_column('credit_transactions', 'attribution_id')
    op.create_index(op.f('idx_credit_pay_date'), 'credit_payments', ['date'], unique=False)
    op.add_column('bank_deposits', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_bank_dep_date'), 'bank_deposits', ['deposit_date'], unique=False)
    # ### end Alembic commands ###
