"""add_active_to_product

Revision ID: 72771b38583e
Revises: f99c5ac53ac4
Create Date: 2026-08-26 18:34:04.869676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72771b38583e'
down_revision: Union[str, Sequence[str], None] = 'f99c5ac53ac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Fix any existing NULL branch_ids in expense_types before making it NOT NULL
    op.execute("""
        UPDATE expense_types
        SET branch_id = (SELECT id FROM branches LIMIT 1)
        WHERE branch_id IS NULL
    """)
    # Make branch_id NOT NULL (skip if already NOT NULL)
    op.execute("""
        DO $$
        BEGIN
            ALTER TABLE expense_types ALTER COLUMN branch_id SET NOT NULL;
        EXCEPTION WHEN others THEN NULL;
        END$$;
    """)
    # Add active column to products (skip if already exists)
    op.execute("""
        DO $$
        BEGIN
            ALTER TABLE products ADD COLUMN active BOOLEAN DEFAULT true;
        EXCEPTION WHEN duplicate_column THEN NULL;
        END$$;
    """)




def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'active')
    op.alter_column('expense_types', 'branch_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
