"""add_active_to_product

Revision ID: 72771b38583e
Revises: f99c5ac53ac4
Create Date: 2026-08-26 18:34:04.869676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72771b38583e'
down_revision: Union[str, Sequence[str], None] = 'f99c5ac53ac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expense_types', 'branch_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.add_column('products', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'active')
    op.alter_column('expense_types', 'branch_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
