"""branch_scoped_product_customer_codes

Revision ID: 865d962e4f2e
Revises: c382309a17a3
Create Date: 2026-08-26 18:15:31.030765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '865d962e4f2e'
down_revision: Union[str, Sequence[str], None] = 'c382309a17a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('customers_code_key'), 'customers', type_='unique')
    op.create_unique_constraint('uq_branch_customer_code', 'customers', ['branch_id', 'code'])
    op.drop_index(op.f('ix_expense_types_branch_id'), table_name='expense_types')
    op.drop_constraint(op.f('fk_expense_types_branch_id'), 'expense_types', type_='foreignkey')
    op.drop_column('expense_types', 'branch_id')
    op.drop_constraint(op.f('products_code_key'), 'products', type_='unique')
    op.create_unique_constraint('uq_branch_product_code', 'products', ['branch_id', 'code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_branch_product_code', 'products', type_='unique')
    op.create_unique_constraint(op.f('products_code_key'), 'products', ['code'])
    op.add_column('expense_types', sa.Column('branch_id', sa.VARCHAR(length=20), server_default=sa.text("'B-01'::character varying"), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_expense_types_branch_id'), 'expense_types', 'branches', ['branch_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_expense_types_branch_id'), 'expense_types', ['branch_id'], unique=False)
    op.drop_constraint('uq_branch_customer_code', 'customers', type_='unique')
    op.create_unique_constraint(op.f('customers_code_key'), 'customers', ['code'])
    # ### end Alembic commands ###
