"""Sync unique constraints for branch_id

Revision ID: c382309a17a3
Revises: b99b6ef4c6d8
Create Date: 2026-08-26 15:32:45.645832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c382309a17a3'
down_revision: Union[str, Sequence[str], None] = 'b99b6ef4c6d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bank_accounts', 'id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.drop_constraint(op.f('bank_accounts_account_number_key'), 'bank_accounts', type_='unique')
    op.create_index(op.f('ix_bank_accounts_branch_id'), 'bank_accounts', ['branch_id'], unique=False)
    op.alter_column('bank_deposits', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_bank_deposits_date'), table_name='bank_deposits')
    op.create_index(op.f('ix_bank_deposits_branch_id'), 'bank_deposits', ['branch_id'], unique=False)
    op.add_column('branches', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('cash_safe_ledger', 'id',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=40),
               existing_nullable=False)
    op.alter_column('cash_safe_ledger', 'denominations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.drop_constraint(op.f('cash_safe_ledger_ledger_date_key'), 'cash_safe_ledger', type_='unique')
    op.drop_index(op.f('idx_cash_date'), table_name='cash_safe_ledger')
    op.create_index(op.f('ix_cash_safe_ledger_branch_id'), 'cash_safe_ledger', ['branch_id'], unique=False)
    op.alter_column('credit_payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('credit_payments_receipt_no_key'), 'credit_payments', type_='unique')
    op.drop_index(op.f('idx_credit_pay_customer'), table_name='credit_payments')
    op.create_index(op.f('ix_credit_payments_branch_id'), 'credit_payments', ['branch_id'], unique=False)
    op.drop_constraint(op.f('credit_payments_payment_mode_check'), 'credit_payments', type_='check')
    op.create_check_constraint('ck_credit_payments_mode', 'credit_payments', "payment_mode IN ('Cash','Cheque','Bank Transfer','NEFT','UPI')")
    op.alter_column('credit_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('credit_transactions_slip_no_key'), 'credit_transactions', type_='unique')
    op.drop_index(op.f('idx_credit_tx_customer'), table_name='credit_transactions')
    op.drop_index(op.f('idx_credit_tx_date'), table_name='credit_transactions')
    op.create_index(op.f('ix_credit_transactions_branch_id'), 'credit_transactions', ['branch_id'], unique=False)
    op.alter_column('customers', 'vehicle_numbers',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('daily_nozzle_meters', 'id',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=40),
               existing_nullable=False)
    op.drop_index(op.f('idx_dnm_date'), table_name='daily_nozzle_meters')
    op.drop_index(op.f('idx_dnm_nozzle'), table_name='daily_nozzle_meters')
    op.drop_constraint(op.f('uq_date_nozzle'), 'daily_nozzle_meters', type_='unique')
    op.create_index(op.f('ix_daily_nozzle_meters_branch_id'), 'daily_nozzle_meters', ['branch_id'], unique=False)
    op.create_unique_constraint('uq_branch_reading_nozzle', 'daily_nozzle_meters', ['branch_id', 'reading_date', 'nozzle_id'])
    op.alter_column('expenses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('expenses_voucher_no_key'), 'expenses', type_='unique')
    op.drop_index(op.f('idx_expenses_date'), table_name='expenses')
    op.drop_index(op.f('idx_expenses_type'), table_name='expenses')
    op.create_index(op.f('ix_expenses_branch_id'), 'expenses', ['branch_id'], unique=False)
    op.drop_index(op.f('idx_frh_date'), table_name='fuel_rate_history')
    op.drop_index(op.f('idx_frh_product'), table_name='fuel_rate_history')
    op.drop_index(op.f('idx_frh_source'), table_name='fuel_rate_history')
    op.drop_constraint(op.f('fuel_rate_history_branch_id_fkey'), 'fuel_rate_history', type_='foreignkey')
    op.drop_column('fuel_rate_history', 'branch_id')
    op.alter_column('master_bank_account_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_mst_bank_acc_t_active'), table_name='master_bank_account_types')
    op.alter_column('master_customer_statuses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_mst_cust_stat_active'), table_name='master_customer_statuses')
    op.alter_column('master_dip_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_mst_dip_types_active'), table_name='master_dip_types')
    op.alter_column('master_expense_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_mst_exp_cat_active'), table_name='master_expense_categories')
    op.alter_column('master_omc_brands', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_mst_omc_brands_active'), table_name='master_omc_brands')
    op.alter_column('master_payment_modes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_mst_pay_modes_active'), table_name='master_payment_modes')
    op.alter_column('master_product_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_mst_prod_cat_active'), table_name='master_product_categories')
    op.alter_column('master_pump_statuses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_mst_pump_stat_active'), table_name='master_pump_statuses')
    op.alter_column('master_shift_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_mst_shift_types_active'), table_name='master_shift_types')
    op.create_index(op.f('ix_meter_readings_branch_id'), 'meter_readings', ['branch_id'], unique=False)
    op.drop_constraint(op.f('nozzles_pump_id_nozzle_no_key'), 'nozzles', type_='unique')
    op.create_index(op.f('ix_nozzles_branch_id'), 'nozzles', ['branch_id'], unique=False)
    op.create_unique_constraint('uq_branch_pump_nozzle', 'nozzles', ['branch_id', 'pump_id', 'nozzle_no'])
    op.create_index(op.f('ix_operators_branch_id'), 'operators', ['branch_id'], unique=False)
    op.alter_column('pos_settlements', 'id',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=40),
               existing_nullable=False)
    op.alter_column('pos_settlements', 'bank_account_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.drop_index(op.f('idx_pos_date'), table_name='pos_settlements')
    op.create_index(op.f('ix_pos_settlements_branch_id'), 'pos_settlements', ['branch_id'], unique=False)
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('products_category_check'), 'products', type_='check')
    op.create_check_constraint('ck_products_category', 'products', "category IN ('FUEL','LUBRICANT')")
    op.drop_constraint(op.f('pumps_pump_no_key'), 'pumps', type_='unique')
    op.create_index(op.f('ix_pumps_branch_id'), 'pumps', ['branch_id'], unique=False)
    op.drop_index(op.f('idx_shifts_date'), table_name='shifts')
    op.drop_index(op.f('idx_shifts_pump'), table_name='shifts')
    op.drop_constraint(op.f('shifts_shift_no_key'), 'shifts', type_='unique')
    op.create_index(op.f('ix_shifts_branch_id'), 'shifts', ['branch_id'], unique=False)
    op.drop_constraint(op.f('shifts_status_check'), 'shifts', type_='check')
    op.create_check_constraint('ck_shifts_status', 'shifts', "status IN ('IN_PROGRESS','CLOSED')")
    op.alter_column('sms_rate_logs', 'parsed_rates',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.drop_index(op.f('idx_sms_received'), table_name='sms_rate_logs')
    op.drop_index(op.f('idx_sms_status'), table_name='sms_rate_logs')
    op.create_index(op.f('ix_sms_rate_logs_branch_id'), 'sms_rate_logs', ['branch_id'], unique=False)
    op.alter_column('tank_dips', 'dip_type',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=60),
               existing_nullable=False)
    op.create_index(op.f('ix_tank_dips_branch_id'), 'tank_dips', ['branch_id'], unique=False)
    op.create_foreign_key(None, 'tank_dips', 'tanks', ['tank_id'], ['id'])
    op.create_index(op.f('ix_tanks_branch_id'), 'tanks', ['branch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tanks_branch_id'), table_name='tanks')
    op.drop_constraint(None, 'tank_dips', type_='foreignkey')
    op.drop_index(op.f('ix_tank_dips_branch_id'), table_name='tank_dips')
    op.alter_column('tank_dips', 'dip_type',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_index(op.f('ix_sms_rate_logs_branch_id'), table_name='sms_rate_logs')
    op.create_index(op.f('idx_sms_status'), 'sms_rate_logs', ['status'], unique=False)
    op.create_index(op.f('idx_sms_received'), 'sms_rate_logs', [sa.literal_column('received_at DESC')], unique=False)
    op.alter_column('sms_rate_logs', 'parsed_rates',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_constraint('ck_shifts_status', 'shifts', type_='check')
    op.create_check_constraint(op.f('shifts_status_check'), 'shifts', "status::text = ANY (ARRAY['IN_PROGRESS'::character varying::text, 'CLOSED'::character varying::text])")
    op.drop_index(op.f('ix_shifts_branch_id'), table_name='shifts')
    op.create_unique_constraint(op.f('shifts_shift_no_key'), 'shifts', ['shift_no'])
    op.create_index(op.f('idx_shifts_pump'), 'shifts', ['pump_id'], unique=False)
    op.create_index(op.f('idx_shifts_date'), 'shifts', ['shift_date'], unique=False)
    op.drop_index(op.f('ix_pumps_branch_id'), table_name='pumps')
    op.create_unique_constraint(op.f('pumps_pump_no_key'), 'pumps', ['pump_no'])
    op.drop_constraint('ck_products_category', 'products', type_='check')
    op.create_check_constraint(op.f('products_category_check'), 'products', "category::text = ANY (ARRAY['FUEL'::character varying::text, 'LUBRICANT'::character varying::text])")
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_pos_settlements_branch_id'), table_name='pos_settlements')
    op.create_index(op.f('idx_pos_date'), 'pos_settlements', ['settlement_date'], unique=False)
    op.alter_column('pos_settlements', 'bank_account_id',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('pos_settlements', 'id',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_index(op.f('ix_operators_branch_id'), table_name='operators')
    op.drop_constraint('uq_branch_pump_nozzle', 'nozzles', type_='unique')
    op.drop_index(op.f('ix_nozzles_branch_id'), table_name='nozzles')
    op.create_unique_constraint(op.f('nozzles_pump_id_nozzle_no_key'), 'nozzles', ['pump_id', 'nozzle_no'])
    op.drop_index(op.f('ix_meter_readings_branch_id'), table_name='meter_readings')
    op.create_index(op.f('idx_mst_shift_types_active'), 'master_shift_types', ['is_active'], unique=False)
    op.alter_column('master_shift_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_mst_pump_stat_active'), 'master_pump_statuses', ['is_active'], unique=False)
    op.alter_column('master_pump_statuses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_mst_prod_cat_active'), 'master_product_categories', ['is_active'], unique=False)
    op.alter_column('master_product_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_mst_pay_modes_active'), 'master_payment_modes', ['is_active'], unique=False)
    op.alter_column('master_payment_modes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_mst_omc_brands_active'), 'master_omc_brands', ['is_active'], unique=False)
    op.alter_column('master_omc_brands', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_mst_exp_cat_active'), 'master_expense_categories', ['is_active'], unique=False)
    op.alter_column('master_expense_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_mst_dip_types_active'), 'master_dip_types', ['is_active'], unique=False)
    op.alter_column('master_dip_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_mst_cust_stat_active'), 'master_customer_statuses', ['is_active'], unique=False)
    op.alter_column('master_customer_statuses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_mst_bank_acc_t_active'), 'master_bank_account_types', ['is_active'], unique=False)
    op.alter_column('master_bank_account_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('fuel_rate_history', sa.Column('branch_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fuel_rate_history_branch_id_fkey'), 'fuel_rate_history', 'branches', ['branch_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_frh_source'), 'fuel_rate_history', ['change_source'], unique=False)
    op.create_index(op.f('idx_frh_product'), 'fuel_rate_history', ['product_id'], unique=False)
    op.create_index(op.f('idx_frh_date'), 'fuel_rate_history', [sa.literal_column('effective_date DESC')], unique=False)
    op.drop_index(op.f('ix_expenses_branch_id'), table_name='expenses')
    op.create_index(op.f('idx_expenses_type'), 'expenses', ['expense_type_id'], unique=False)
    op.create_index(op.f('idx_expenses_date'), 'expenses', ['date'], unique=False)
    op.create_unique_constraint(op.f('expenses_voucher_no_key'), 'expenses', ['voucher_no'])
    op.alter_column('expenses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_branch_reading_nozzle', 'daily_nozzle_meters', type_='unique')
    op.drop_index(op.f('ix_daily_nozzle_meters_branch_id'), table_name='daily_nozzle_meters')
    op.create_unique_constraint(op.f('uq_date_nozzle'), 'daily_nozzle_meters', ['reading_date', 'nozzle_id'])
    op.create_index(op.f('idx_dnm_nozzle'), 'daily_nozzle_meters', ['nozzle_id'], unique=False)
    op.create_index(op.f('idx_dnm_date'), 'daily_nozzle_meters', ['reading_date'], unique=False)
    op.alter_column('daily_nozzle_meters', 'id',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('customers', 'vehicle_numbers',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.drop_index(op.f('ix_credit_transactions_branch_id'), table_name='credit_transactions')
    op.create_index(op.f('idx_credit_tx_date'), 'credit_transactions', ['date'], unique=False)
    op.create_index(op.f('idx_credit_tx_customer'), 'credit_transactions', ['customer_id'], unique=False)
    op.create_unique_constraint(op.f('credit_transactions_slip_no_key'), 'credit_transactions', ['slip_no'])
    op.alter_column('credit_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('ck_credit_payments_mode', 'credit_payments', type_='check')
    op.create_check_constraint(op.f('credit_payments_payment_mode_check'), 'credit_payments', "payment_mode::text = ANY (ARRAY['Cash'::character varying::text, 'Cheque'::character varying::text, 'Bank Transfer'::character varying::text, 'NEFT'::character varying::text, 'UPI'::character varying::text])")
    op.drop_index(op.f('ix_credit_payments_branch_id'), table_name='credit_payments')
    op.create_index(op.f('idx_credit_pay_customer'), 'credit_payments', ['customer_id'], unique=False)
    op.create_unique_constraint(op.f('credit_payments_receipt_no_key'), 'credit_payments', ['receipt_no'])
    op.alter_column('credit_payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_cash_safe_ledger_branch_id'), table_name='cash_safe_ledger')
    op.create_index(op.f('idx_cash_date'), 'cash_safe_ledger', ['ledger_date'], unique=False)
    op.create_unique_constraint(op.f('cash_safe_ledger_ledger_date_key'), 'cash_safe_ledger', ['ledger_date'])
    op.alter_column('cash_safe_ledger', 'denominations',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('cash_safe_ledger', 'id',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_column('branches', 'updated_at')
    op.drop_index(op.f('ix_bank_deposits_branch_id'), table_name='bank_deposits')
    op.create_index(op.f('idx_bank_deposits_date'), 'bank_deposits', ['deposit_date'], unique=False)
    op.alter_column('bank_deposits', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_bank_accounts_branch_id'), table_name='bank_accounts')
    op.create_unique_constraint(op.f('bank_accounts_account_number_key'), 'bank_accounts', ['account_number'])
    op.alter_column('bank_accounts', 'id',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
