"""restore_expense_type_branch_id

Revision ID: f99c5ac53ac4
Revises: 865d962e4f2e
Create Date: 2026-08-26 18:16:02.020464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f99c5ac53ac4'
down_revision: Union[str, Sequence[str], None] = '865d962e4f2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_types', sa.Column('branch_id', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_expense_types_branch_id'), 'expense_types', ['branch_id'], unique=False)
    op.create_foreign_key(None, 'expense_types', 'branches', ['branch_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expense_types', type_='foreignkey')
    op.drop_index(op.f('ix_expense_types_branch_id'), table_name='expense_types')
    op.drop_column('expense_types', 'branch_id')
    # ### end Alembic commands ###
